import type { Argument, Command, Option } from "commander";

const cell = (value: string): string =>
  value.replaceAll("|", "\\|").replaceAll("\n", " ");

const display = (value: unknown): string => {
  const serialized = JSON.stringify(value);
  return serialized === undefined ? String(value) : serialized;
};

const pathOf = (command: Command): string => {
  const names: string[] = [];
  let current: Command | null = command;
  while (current) {
    names.unshift(current.name());
    current = current.parent;
  }
  return names.join(" ");
};

const argumentTerm = (argument: Argument): string => {
  const name = `${argument.name()}${argument.variadic ? "..." : ""}`;
  return argument.required ? `<${name}>` : `[${name}]`;
};

const optionRow = (option: Option): string[] => [
  `\x60${option.flags}\x60`,
  option.description,
  option.defaultValue === undefined ? "" : `\x60${display(option.defaultValue)}\x60`,
  option.argChoices?.join(", ") ?? "",
];

const table = (headings: string[], rows: string[][]): string[] =>
  rows.length === 0
    ? []
    : [
        `| ${headings.join(" | ")} |`,
        `| ${headings.map(() => "---").join(" | ")} |`,
        ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
        "",
      ];

const inheritedOptions = (command: Command): Option[] => {
  const ancestors: Command[] = [];
  let current = command.parent;
  while (current) {
    ancestors.unshift(current);
    current = current.parent;
  }
  return ancestors.flatMap((ancestor) =>
    ancestor.options.filter((option) => !option.hidden),
  );
};

const renderCommand = (command: Command): string[] => {
  const path = pathOf(command);
  const lines = [
    `## \x60${path}\x60`,
    "",
    command.description(),
    "",
    `**Usage:** \x60${path} ${command.usage()}\x60`,
    "",
  ];

  const argumentRows = command.registeredArguments.map((argument) => [
    `\x60${argumentTerm(argument)}\x60`,
    argument.description,
    argument.required ? "yes" : "no",
    argument.variadic ? "yes" : "no",
    argument.defaultValue === undefined
      ? ""
      : `\x60${display(argument.defaultValue)}\x60`,
    argument.argChoices?.join(", ") ?? "",
  ]);
  if (argumentRows.length > 0) {
    lines.push(
      "### Arguments",
      "",
      ...table(
        ["Argument", "Description", "Required", "Variadic", "Default", "Choices"],
        argumentRows,
      ),
    );
  }

  const localRows = command.options
    .filter((option) => !option.hidden)
    .map(optionRow);
  if (localRows.length > 0) {
    lines.push(
      "### Options",
      "",
      ...table(["Option", "Description", "Default", "Choices"], localRows),
    );
  }

  const inheritedRows = inheritedOptions(command).map(optionRow);
  if (inheritedRows.length > 0) {
    lines.push(
      "### Inherited global options",
      "",
      ...table(["Option", "Description", "Default", "Choices"], inheritedRows),
    );
  }

  const childRows = command.commands.map((child) => [
    `\x60${pathOf(child)}\x60`,
    child.description(),
  ]);
  if (childRows.length > 0) {
    lines.push(
      "### Subcommands",
      "",
      ...table(["Command", "Description"], childRows),
    );
  }
  return lines;
};

const flatten = (command: Command): Command[] => [
  command,
  ...command.commands.flatMap(flatten),
];

/** Renders stable Markdown from a fully registered Commander command tree. */
export const renderCommandReference = (program: Command): string =>
  [
    "# GoodLinks CLI Command Reference",
    "",
    "<!-- Generated by pnpm run skill:generate. Do not edit by hand. -->",
    "",
    "Use installed leaf \x60--help\x60 as the final authority if it differs from this file.",
    "",
    ...flatten(program).flatMap(renderCommand),
  ].join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
